service: territory-marker

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [territories, Arn]

environment:
  TABLE_NAME:
    Ref: territories

package:
  patterns:
    - "!./**"
    - "./src/**"

functions:
  listTerritories:
    handler: src/territory-update/territory-list
    events:
      - http:
          path: territory/list
          method: get
          cors: true
  updateTerritory:
    handler: src/territory-update/main
    events:
      - http:
          path: territory
          method: put
          cors: true

resources:
  - Resources:
      territories:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: territories
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: N
            - AttributeName: name
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
            - AttributeName: name
              KeyType: RANGE
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
